---
deployment:
  tasks:
    - export DEPLOYPATH=/home/projectv/fastcdpapi.projectvault.pk/cdp-backend/
    - cd $DEPLOYPATH
    - git pull origin main  # Pull latest changes
    - npm install           # Install dependencies
    - touch tmp/restart.txt # Restart if using Passenger
