---
deployment:
  tasks:
    - export DEPLOYPATH=/home/projectv/fastcdpapi.projectvault.pk/cdp-backend/
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - npm install --production
    - touch tmp/restart.txt
