---
deployment:
  tasks:
    - export DEPLOYPATH=/home/projectv/fastcdpapi.projectvault.pk/cdp-backend/
    - rsync -av --exclude='cdp-frontend' cdp-backend/ $DEPLOYPATH
    - cd $DEPLOYPATH
    - npm install --production
    - touch tmp/restart.txt
